buildscript {
    repositories {
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
    }
}

allprojects {
    version = '1.0'
    ext {
        appName = "Donjon de Naheulbeuk Fan Game"
        gdxVersion = '1.12.1'
        gdxControllersVersion = '2.2.3'
    }

    repositories {
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://jitpack.io" }
    }
}
