buildscript {
    repositories {
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }
    }
}

allprojects {
    version = '1.0'
    ext {
        appName = "Donjon de Naheulbeuk Fan Game"
        gdxVersion = '1.12.1'
        gdxControllersVersion = '2.2.3'
    }

    repositories {
            if (changed) {
                file.setText(content, 'UTF-8')
                println "Fixed: \\"
            }
        }
    }
}

allprojects {
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}

